/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DFAPropertiesWin.java
 *
 * Created on 20.09.2009, 19:21:15
 */
package gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.filechooser.FileFilter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import models.Dfa;
import models.DfaTransitionTableModel;
import models.State;

/**
 *
 * @author Fabian
 */
public class DFAPropertiesWin extends JDialog {

    private Dfa dfa = null;
    private DFAMainWin dFAMainWin = null;
    private DfaTransitionTableModel tm;

    /**
     * Creates new form DFAPropertiesWin
     */
    public DFAPropertiesWin() {
        initComponents();
        centreWindow(this);
        this.setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        tableDelta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAlphabet = new javax.swing.JTextArea();
        buttonCancel = new javax.swing.JButton();
        buttonOK = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textacceptingstates = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textstates = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        labelstartstate = new javax.swing.JLabel();
        exportTableBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DFA Properties");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane4.setAutoscrolls(true);

        tableDelta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tableDelta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDelta.setEnabled(false);
        jScrollPane4.setViewportView(tableDelta);

        jLabel1.setText("Description (will be shown in the sidebar)");

        textDescription.setColumns(20);
        textDescription.setLineWrap(true);
        textDescription.setRows(5);
        jScrollPane1.setViewportView(textDescription);

        jLabel3.setText("Alphabet (Sigma)");

        textAlphabet.setBackground(new java.awt.Color(236, 233, 222));
        textAlphabet.setColumns(20);
        textAlphabet.setEditable(false);
        textAlphabet.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        textAlphabet.setLineWrap(true);
        textAlphabet.setRows(5);
        jScrollPane2.setViewportView(textAlphabet);

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonOK.setText("Ok");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        jLabel4.setText("Transition function States x Alphabet (Delta)");

        jLabel5.setText("States (Q)");

        textacceptingstates.setBackground(new java.awt.Color(236, 233, 222));
        textacceptingstates.setColumns(20);
        textacceptingstates.setEditable(false);
        textacceptingstates.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        textacceptingstates.setLineWrap(true);
        textacceptingstates.setRows(5);
        jScrollPane3.setViewportView(textacceptingstates);

        jLabel6.setText("Accepting states (F)");

        textstates.setBackground(new java.awt.Color(236, 233, 222));
        textstates.setColumns(20);
        textstates.setEditable(false);
        textstates.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        textstates.setLineWrap(true);
        textstates.setRows(5);
        jScrollPane5.setViewportView(textstates);

        jLabel2.setText("Start state:");

        labelstartstate.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        labelstartstate.setText("q0");

        exportTableBtn.setText("Export Table");
        exportTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportTableBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(160, 160, 160)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelstartstate))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(exportTableBtn, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelstartstate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exportTableBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadData();
    }//GEN-LAST:event_formWindowOpened

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        if (saveData()) {
            setVisible(false);
            dFAMainWin.updateSidebar();
            dispose();
        }
    }//GEN-LAST:event_buttonOKActionPerformed

    private void exportTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportTableBtnActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Choose file...");
        fc.setFileFilter(new FileFilter() {
                @Override
                public boolean accept(File f) {
                    return f.getName().toLowerCase().endsWith(".tsv") || f.isDirectory();
                }
                @Override
                public String getDescription() {
                    return "Tab Seperated Value(*.tsv)";
                }
            });
        fc.setMultiSelectionEnabled(false);
        int retVal = fc.showSaveDialog(this);
        if (retVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            tableToFile(file);

        }
    }//GEN-LAST:event_exportTableBtnActionPerformed

    public Dfa getDfa() {
        return dfa;
    }

    public void setDfa(Dfa dfa) {
        this.dfa = dfa;
    }

    public DFAMainWin getdFAMainWin() {
        return dFAMainWin;
    }

    public void setdFAMainWin(DFAMainWin dFAMainWin) {
        this.dFAMainWin = dFAMainWin;
    }

    private void loadData() {
      this.textDescription.setText(this.dfa.getDescription());

      ArrayList alphabet = getdFAMainWin().getDfaSim().getAlphabetFromTransitions();
      String s = getCommaStringFromArrayList(alphabet);
      this.textAlphabet.setText("{" + s + "}");

      String startState = "<html><i>none</i></html>";
      if (this.dfa.getStartState() != null) {
        startState = this.dfa.getStartState().getState_Properties().getName();
      }
      this.labelstartstate.setText(startState);

      ArrayList listStates = new ArrayList();
      for (int i = 0; i < this.dfa.getStates().size(); i++) {
        listStates.add(((State)this.dfa.getStates().get(i)).getState_Properties().getName());
      }
      this.textstates.setText("{" + getCommaStringFromArrayList(listStates) + "}");

      listStates = new ArrayList();
      for (int i = 0; i < this.dfa.getStates().size(); i++) {
        if (((State)this.dfa.getStates().get(i)).getIsFinalState()) {
          listStates.add(((State)this.dfa.getStates().get(i)).getState_Properties().getName());
        }
      }
      this.textacceptingstates.setText("{" + getCommaStringFromArrayList(listStates) + "}");

      this.tm = new DfaTransitionTableModel();
      this.tm.setAlphabet(alphabet);
      this.tm.setDfa(this.dfa);
      this.tableDelta.setModel(this.tm);
      JTableHeader th = this.tableDelta.getTableHeader();
      TableColumnModel tcm = th.getColumnModel();
      for (int i = 0; i < tcm.getColumnCount(); i++) {
        TableColumn tc = tcm.getColumn(i);
        if (i == 0)
          tc.setHeaderValue("δ");
        else {
          tc.setHeaderValue(alphabet.get(i - 1));
        }
      }
      th.repaint();
    }

    
    public void tableToFile(File file) {
        
        FileWriter outFile = null;
        try {
            outFile = new FileWriter(file);
            
            //Write column names
            
            JTableHeader th = tableDelta.getTableHeader();
            TableColumnModel tcm = th.getColumnModel();
            for (int i = 0;i<tm.getColumnCount();i++ ) {
                TableColumn tc = tcm.getColumn(i);
                outFile.write("\""+tc.getHeaderValue() + "\""+((tm.getColumnCount()-1)==i ? "" : ","));
            }
            outFile.write("\n");
            
            for (int i=0; i<tm.getRowCount();i++) {
                for(int j=0; j<tm.getColumnCount();j++) {
                    outFile.write("\""+tm.getValueAt(i,j).toString() + "\""+((tm.getColumnCount()-1)==j ? "" : ","));
                }
                outFile.write("\n");
            }
            
        } catch (IOException ex) {
            Logger.getLogger(DfaTransitionTableModel.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                outFile.close();
                JOptionPane.showMessageDialog(null, "Succesfully exported table");
            } catch (IOException ex) {
                Logger.getLogger(DfaTransitionTableModel.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "An error occured exporting the table");
            }
        }
        
        
    }

    private String getCommaStringFromArrayList(ArrayList<String> a) {
        if (a.size() == 0) {
            return "";
        } else {
            String s = "";
            for (int i = 0; i < a.size(); i++) {
                if (i != a.size() - 1) {
                    s = s + a.get(i) + ",";
                } else {
                    s = s + a.get(i);
                }
            }
            return s;
        }

    }

    private boolean saveData() {
        dfa.setDescription(textDescription.getText());
        dFAMainWin.repaint();
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DFAPropertiesWin().setVisible(true);

            }
        });
    }

    public static void centreWindow(JDialog frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton exportTableBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelstartstate;
    private javax.swing.JTable tableDelta;
    private javax.swing.JTextArea textAlphabet;
    private javax.swing.JTextArea textDescription;
    private javax.swing.JTextArea textacceptingstates;
    private javax.swing.JTextArea textstates;
    // End of variables declaration//GEN-END:variables
}
