/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DFAPropertiesWin.java
 *
 * Created on 20.09.2009, 19:21:15
 */

package gui;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Dfa;

/**
 *
 * @author Fabian
 */
public class DFAWelcomeWin extends javax.swing.JDialog {

    private DFAMainWin dFAMainWin = null;
    private final static int WINDOW_WIDTH = 570;
    private final static int WINDOW_HEIGHT = 335;
    private final static String wikiUri = "http://www.wikipedia.org/wiki/Deterministic_finite-state_machine";

    /** Creates new form DFAPropertiesWin */
    public DFAWelcomeWin() {
        initComponents();
        this.setSize(new Dimension(WINDOW_WIDTH, WINDOW_HEIGHT));
        centreWindow(this);
        this.setModal(true);
        labelUri.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    public DFAWelcomeWin(boolean checkShowAlways) {
        this();
        this.checkShowWelcome.setSelected(checkShowAlways);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonOK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelUri = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        checkShowWelcome = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Learning Center");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        buttonOK.setText("close");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });
        getContentPane().add(buttonOK);
        buttonOK.setBounds(450, 240, 90, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel2.setText("Knowledge");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 220, 500, 30);

        labelUri.setFont(new java.awt.Font("Tahoma", 0, 12));
        labelUri.setForeground(new java.awt.Color(0, 51, 255));
        labelUri.setText(this.wikiUri);
        labelUri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelUriMouseClicked(evt);
            }
        });
        getContentPane().add(labelUri);
        labelUri.setBounds(30, 270, 560, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Welcome!");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 10, 500, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel6.setText("This program allows you to design Deterministic Finite Automata graphically and simulate them.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 50, 560, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel7.setText("A string search DFA, which accepts when a word ends with 'abc'.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 180, 490, 20);

        jButton1.setText("Example 2");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 170, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel4.setText("Examples");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 100, 500, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel8.setText("It has a tool help bar on the right side, which explains the basic operations.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 70, 560, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel9.setText("You can find more about the theory of DFA at");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 250, 560, 15);

        jButton2.setText("Example 1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 140, 100, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("A 01-bitstream automaton, which accepts even numbers of ones.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 150, 490, 20);

        checkShowWelcome.setBackground(new Color(0,0,0,0));
        checkShowWelcome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkShowWelcome.setSelected(true);
        checkShowWelcome.setText("Show always on startup");
        checkShowWelcome.setToolTipText("Click here if you don't want this window to come up with every start of the program");
        checkShowWelcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkShowWelcomeActionPerformed(evt);
            }
        });
        getContentPane().add(checkShowWelcome);
        checkShowWelcome.setBounds(390, 10, 160, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/art.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-50, -10, 650, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   
    }//GEN-LAST:event_formWindowOpened

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed

            setVisible(false);
            dispose();
    }//GEN-LAST:event_buttonOKActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadDfa(2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        loadDfa(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void labelUriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUriMouseClicked
        URI uri;
        try {
            uri = new URI(wikiUri);
            if (java.awt.Desktop.isDesktopSupported()) {
                try {
                    java.awt.Desktop.getDesktop().browse(uri);
                } catch (IOException ex) {
                    System.err.println(ex.getMessage());
                }
            }
        } catch (URISyntaxException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_labelUriMouseClicked

    private void checkShowWelcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkShowWelcomeActionPerformed
        File config = DFAMainWin.getConfigFile();
        if(checkShowWelcome.isSelected()) {
            if(config.exists()) {
                //delete
                if(!config.delete()) {
                    System.err.println("Could not delete config file properly.");
                } else {
                    dFAMainWin.setShowWelcomeWindow(true);
                }
            }
        } else {
            if(!config.exists()) {
                try {
                    config.createNewFile();
                    dFAMainWin.setShowWelcomeWindow(false);
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_checkShowWelcomeActionPerformed

    private void loadDfa(int number) {
        Dfa d = dFAMainWin.getDfaSim().getDfaEditor().getExampleDFA(number);
        dFAMainWin.openDFA(d);
        setVisible(false);
        dispose();
    }


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DFAWelcomeWin().setVisible(true);
            }
        });
    }

    public DFAMainWin getdFAMainWin() {
        return dFAMainWin;
    }

    public void setdFAMainWin(DFAMainWin dFAMainWin) {
        this.dFAMainWin = dFAMainWin;
    }


   public static void centreWindow(javax.swing.JDialog frame) {
    Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
    int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
    int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
    frame.setLocation(x, y);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOK;
    private javax.swing.JCheckBox checkShowWelcome;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelUri;
    // End of variables declaration//GEN-END:variables



}
